apiVersion: v1
kind: ConfigMap
metadata:
  name: frontendconfig
  namespace: {{ .Release.Namespace | quote }}
data:
    keycloak.json: |-
      {
        "realm": "openapi",
        "auth-server-url": "http://160.40.50.74:8180/",
        "ssl-required": "external",
        "resource": "public-frontend",
        "public-client": true,
        "confidential-port": 0
      }
